environment                = "dev"
project_name               = "pdds-2-quarter-project-group-6"
bucket_name                = "pdds-2-quarter-project-group-6-s3"
app_bucket_name            = "app-pdds-2-quarter-project-group-6-s3"
region                     = "us-west-2"
ami_id                     = "ami-0ddb64e71e68cf624"
instance_type              = "t4g.nano"
vpc_cidr                   = "10.0.0.0/16"
public_subnet_cidrs        = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidrs       = ["10.0.11.0/24", "10.0.12.0/24"]
availability_zones         = ["us-west-2a", "us-west-2b"]
name                       = "group-6"
default_port               = 8080
ingress_port               = 80
private_port               = 443
health_check_path          = "/health"
queue_name                 = "tickets"
max_receive_count          = 3
message_retention_seconds  = 86400
visibility_timeout_seconds = 30
architecture               = "arm64"
memory_size                = 64
schedule_expression        = "rate(10 minutes)"
scheduler_timezone         = "America/Guatemala"